# api-chart/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
spec:
  selector:
    app: {{ include "api-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
