# api-chart/values.yaml

image:
  repository: cuong111111/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

mongodb:
  host: mongo
  port: 27017
  database: vdt2024
